# Travis example for Identifier created by Rafael Garibotti

sudo: true
language: c
after_success:
  - bash <(curl -s https://codecov.io/bash)
compiler:
  - gcc
before_install:
  - sudo apt-get -y install cppcheck valgrind
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd crypt; make
#  - make test
