/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "identifier.h"



/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

extern void Input1(void);
extern void Input2(void);
extern void Input3(void);
extern void Input4(void);
extern void Input5(void);
extern void NumeroNoMeio(void);

extern void PrimeiroNumero(void);
extern void Numero(void);
extern void NumeroMaxCh(void);
extern void NumeroMinCh(void);
extern void StringVazio(void);
extern void CaracterEspecial(void);
extern void SomenteNumeros(void);







/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/identifierTest.c");
  //Devem passar
  RUN_TEST(Input1, 27);
  RUN_TEST(Input2, 33);
  RUN_TEST(Input3, 39);
  RUN_TEST(Input4, 45);
  RUN_TEST(Input5, 51);
  RUN_TEST(NumeroNoMeio, 64);

  //Devem falhar
  RUN_TEST(PrimeiroNumero, 76);
  RUN_TEST(Numero, 82);
  RUN_TEST(NumeroMaxCh, 89);
  RUN_TEST(StringVazio, 103);
  RUN_TEST(CaracterEspecial, 110);
  RUN_TEST(SomenteNumeros, 117);


  return (UnityEnd());
}